### ISSUE TITLE
Conflict with CoreProtect & WorldEdit

### ISSUE THREAD

**Issue by FireController1847** [Jikoo/CreeperHeal#1]
Hello, CoreProtect, WorldEdit, and CreeperHeal developers. I have found a joint issue when using all three plugins together that I'm hoping we can work together to solve.

The issue is that CoreProtect does not log blocks that are broken by fire, water, or lava when all three plugins are installed.

My versions include:
PaperMC 1.16.5 Build 466
CoreProtect 19.4
CreeperHeal 7.0.5 (Jikoo Fork, Release 3) 
WorldEdit 7.2.2

The issue occurs using default configurations. Steps to reproduce are:
1. Create a new server with the corresponding plugins
2. Place a 4x4x1 area of wood planks (or any other burnable substance)
3. Burn it
4. Run `/co rollback radius:10 time:5m user:#fire`
5. Confirm with `/co near` that there are no reports of `#fire broke oak_planks`

I have absolutely no clue what could be causing the issue. At a complete guess, possibly two plugins are blocking some sort of block break event, causing the third (cp) to not detect it. But that's just a guess.

Here are the corresponding issues for the other two plugins:
CoreProtect: https://discord.gg/NvndZ7xM9p (#bugs)
CreeperHeal: https://github.com/EngineHub/WorldEdit/issues/1669

**Comment by Jikoo** [comment]
Unfortunately, since CoreProtect is closed source, I can't help you track this down. I suggest you disable CH's fire restoration feature.
